### PR TITLE
fix(install): probe gsd-sdk for `query` capability, not just PATH (#2414)

### LINKED ISSUE #2393: [1.37.1] `gsd-sdk query` calls fail — installed `@gsd-build/sdk@0.1.0` exposes only `run|auto|init`, no `query` subcommand
## Summary

After updating to v1.37.1, any workflow or agent that invokes `gsd-sdk query <command>` fails because the installed npm package `@gsd-build/sdk@0.1.0` exposes only `run | auto | init` subcommands — there is no `query` dispatcher.

The CHANGELOG for v1.36 describes migrating call sites from `gsd-tools.cjs` to `gsd-sdk query <handler>`, but the `@gsd-build/sdk` package shipped to npm does not implement the `query` dispatcher those workflows depend on.

## Versions

- GSD: v1.37.1 (also reproduces on v1.36.0; works on v1.34.2)
- `@gsd-build/sdk`: 0.1.0 — only version published to npm; `npm view @gsd-build/sdk versions` returns `["0.1.0"]`
- Node: v22.20.0 (via nvm)
- Runtime: Claude Code 2.x on macOS (darwin 25.5.0)

## Reproduction

```bash
$ npm view @gsd-build/sdk version
0.1.0

$ gsd-sdk query validate.health
Error: Expected "gsd-sdk run <prompt>", "gsd-sdk auto", or "gsd-sdk init [input]"
Usage: gsd-sdk <command> [args] [options]

Commands:
  run <prompt>          Run a full milestone from a text prompt
  auto                  Run the full autonomous lifecycle ...
  init [input]          Bootstrap a new project from a PRD ...
```

Or invoke `/gsd-health` from Claude Code — it fails on the first `gsd-sdk query` call in `workflows/health.md`.

## Impact

~40 call sites in v1.37.1 invoke `gsd-sdk query`:

- `workflows/health.md` → `gsd-sdk query validate.health`
- `workflows/execute-plan.md` → `verify.key-links`, `verify.artifacts`
- `workflows/execute-phase.md` → `config-get`, `commit`, `roadmap.update-plan-progress`
- `workflows/progress.md` → `state.load`
- `workflows/complete-milestone.md` → `commit`
- `workflows/profile-user.md` → `frontmatter.get`
- (+ many others — `grep -r "gsd-sdk query" ~/.claude/get-shit-done/`)

Many call sites swallow failures (`|| echo "…"`) so the symptom is silent fallback to defaults. Hard-fail paths like `/gsd-health` error immediately.

## Expected

Either:

1. `@gsd-build/sdk` ships the `query` dispatcher that v1.36+ workflows depend on, or
2. Workflows call `gsd-tools.cjs` directly (as v1.34.2 did — 55 call sites, all functional).

## Workaround

Downgrade to the last npm-published pre-migration release:

```bash
npx get-shit-done-cc@1.34.2 --global
```

v1.35.0 was tagged on GitHub but never published to npm (`npm view get-shit-done-cc versions` skips from `1.34.2` to `1.36.0`), so `1.34.2` is the last npm-reachable working version.

### LINKED ISSUE #2414: [bug] Skills reference non-existent gsd-sdk query subcommand
### GSD Version
1.37.1

### Runtime
Claude Code

### Operating System
macOS

### Node.js Version
v24.14.0

### Shell
/bin/zsh

### Installation Method
Updated from a previous version

---

### What happened?
After a fresh install via `npx get-shit-done-cc@latest --claude --global`, GSD skills fail with "gsd-sdk not found" or "Unknown command" errors when they invoke `gsd-sdk query <subcommand>`.

The skills reference `gsd-sdk query` subcommands that do not exist in the installed `gsd-sdk` CLI:

```bash
# Skills invoke like this (e.g., gsd-manager, gsd-autonomous):
gsd-sdk query init.manager
gsd-sdk query init.phase-op "1"
gsd-sdk query roadmap.analyze
gsd-sdk query frontmatter.get .planning/STATE.md status

# But gsd-sdk only supports:
gsd-sdk run <prompt>
gsd-sdk auto
gsd-sdk init [input]
```

### What did you expect?
Skills that reference `gsd-sdk query X.Y` should work out of the box after installation.

### Steps to reproduce
1. Run `npm install -g get-shit-done-cc`
2. Run `get-shit-done-cc --claude --global`
3. Attempt to use any GSD skill that calls `gsd-sdk query` (e.g., `/gsd-manager`)
4. Error: `gsd-sdk: command not found` or `Error: Expected "gsd-sdk run <prompt>"...`

### Error output / logs
```
$ which gsd-sdk
gsd-sdk not found

$ gsd-sdk query init.phase-op "1"
Error: Expected "gsd-sdk run <prompt>", "gsd-sdk auto", or "gsd-sdk init [input]"
```

### Investigation
The installed `gsd-sdk` CLI is provided by `@gsd-build/sdk` npm package and only supports three commands: `run`, `auto`, `init`. There is no `query` subcommand.

The `query` subcommand logic exists in a **different** binary: `gsd-tools.cjs` located at:
```
~/.claude/get-shit-done/bin/gsd-tools.cjs
```

`gsd-tools.cjs` supports the commands skills expect:
```
gsd-tools.cjs init manager
gsd-tools.cjs init phase-op "1"
gsd-tools.cjs roadmap analyze
gsd-tools.cjs frontmatter get .planning/STATE.md status
```

### How often does this happen?
Every time (100% reproducible)

### Impact
Major — Core feature is broken, no workaround

### Additional context
- `ls -la ~/.claude/get-shit-done/bin/` shows `gsd-tools.cjs` exists
- Skills reference: `gsd-sdk query init.manager` in at least:
  - `gsd-manager/SKILL.md`
  - `gsd-autonomous/SKILL.md`
  - `gsd-quick/SKILL.md`
  - `gsd-add-backlog/SKILL.md`
  - `gsd-workstreams/SKILL.md`
  - And 12+ other skills

- npm packages installed:
  - `get-shit-done-cc@1.37.1` → provides skills, workflows, hooks
  - `@gsd-build/sdk@0.1.0` → provides `gsd-sdk` CLI (but without `query` command)
  - `gsd-tools.cjs` is bundled inside `get-shit-done-cc` but NOT linked to PATH

**The issue**: The README states `gsd-sdk` is "installed automatically" but the installed `gsd-sdk` does not have the `query` subcommand that all skills depend on.

### PR DESCRIPTION
**Pull request by gauravagnihotristla**
## Summary

- Replace `which gsd-sdk` probe in `installSdkIfNeeded()` with a capability probe that runs `gsd-sdk --help` and rebuilds if the output lacks `query`
- Add a static regression test so the probe wiring can't silently revert
- Add `[Unreleased] ### Fixed` CHANGELOG entry referencing #2414

Fixes #2414. Builds on #2386 (which already rewired fresh installs to build from in-repo `sdk/` source). This PR closes the remaining upgrade-path gap: users who installed v1.37.1 have the stale `@gsd-build/sdk@0.1.0` on PATH, and the old probe short-circuited the rebuild, leaving them broken after upgrade.

## Related issues (same root cause)

All symptoms of the same stale/missing `@gsd-build/sdk@0.1.0` distribution gap:

- Closes #2414 — upgrade-path probe (this PR)
- Closes #2393 — `gsd-sdk query` calls fail; installed `@gsd-build/sdk@0.1.0` exposes only `run|auto|init` (stale SDK on PATH → this PR's fix)
- Refs #2408 — workflow files reference `gsd-sdk` but installed CLI is `gsd-tools` (reporter had no SDK on PATH; that scenario is fixed by #2386, not this PR)
- Refs #2334 — fresh-install crash, already closed by #2386
- Refs #2309 — maintainer root-cause analysis. This PR covers the upgrade-path remediation; the silent-fallback hardening (fail loud on missing `query`) is intentionally out of scope.

## Why the capability probe

`gsd-sdk --help` is cheap, deterministic, exit-0 on both versions, and directly tests the capability every `/gsd-*` skill depends on. Robust to future SDK version-number changes. Timeout + non-zero exit + missing string all fall through to the rebuild path — an unresponsive SDK is not a usable SDK.

| State on machine | Old behavior | New behavior |
|---|---|---|
| No gsd-sdk | build from source | build from source |
| Stale 0.1.0 on PATH | **skip build (bug)** | **build from source (fix)** |
| Current SDK on PATH | skip build | skip build |
| `--sdk` flag | force build | force build |
| `--no-sdk` flag | skip entirely | skip entirely |

## Test plan

- [x] `node --test tests/bugs-1656-1657.test.cjs` — 8/8 pass, including the new `#2414` regression test
- [x] `npm test` — full suite green (4145 pass, 0 fail, 8 skipped)
- [x] Manual: simulated probe against stale 0.1.0 on the author's machine — decision was `TRIGGER BUILD` as expected
- [ ] Maintainer verification: run installer on a machine with stale 0.1.0 and confirm rebuild succeeds

## Design spec

[`docs/superpowers/specs/2026-04-18-issue-2414-stale-sdk-probe-design.md`](https://github.com/gsd-build/get-shit-done/blob/main/docs/superpowers/specs/2026-04-18-issue-2414-stale-sdk-probe-design.md) (included in this branch).

Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **Bug Fixes**
  * Enhanced installer robustness during upgrades by automatically detecting stale or broken globally installed SDK versions and rebuilding from in-repo source when needed. Detection now verifies SDK capabilities rather than relying solely on binary presence. Missing binaries, timeouts, and command failures also trigger a rebuild to ensure compatibility.

### CODE REVIEW

**Review by trek-e — APPROVED** [review]
The capability probe approach is sound and the fix is correct.

The core change — replacing `which gsd-sdk` with `gsd-sdk --help | grep query` — correctly handles all four states in the behavior matrix (no SDK, stale 0.1.0, current SDK, forced rebuild). Timeout, ENOENT, and non-zero exit all fall through to the build path without special-casing, which is the right failure mode.

The regression test in `tests/bugs-1656-1657.test.cjs` uses source-level assertions (regex against the installer source) to guard against reverting to the `which`-only probe. This is consistent with the existing tests in that file.

One observation on future robustness: the probe checks for the literal string `'query'` in stdout. If the `--help` output format changes to spell it differently (e.g., `'query (subcommands)'` is fine, but renaming to `'lookup'` would break the probe silently). This is documented in the design spec's edge cases section. Acceptable risk given the regression test guards it.

The spec doc (`docs/superpowers/specs/...`) is large (159 lines) but accurately describes the design. Including it in the PR is not harmful.

The lone CodeRabbit finding (missing `js` language tag in a fenced block in the spec doc) was addressed in the final commit (`d1879eb`).

Approve.

**Comment by trek-e** [comment]
CodeRabbit finding audit: single finding confirmed resolved. One CodeRabbit finding was a missing language tag on a fenced code block in the spec doc around line 116. Verified against the current branch: the block has the js language tag added in commit d1879eb. trek-e adversarial review also confirmed this. No open CodeRabbit findings remain on this PR.

**Comment by trek-e** [comment]
Rebased onto current `main` (was 22 commits behind). Conflicts resolved:

- `bin/install.js` — kept the capability-probe logic from this PR (`gsd-sdk --help` + `query` string check) over HEAD's simpler `resolveGsdSdk()` PATH-only check. The whole point of the PR.
- `CHANGELOG.md` — kept both entries side-by-side (your #2414 stale-SDK probe fix and main's #2406 injection-scanner fix; neither supersedes the other).

Three small commits added on top of your series:

1. `docs(spec): add js language tag to fenced block (MD040)` — the original final commit from your series (`bf87115c`) replayed cleanly after rebase; kept it.
2. `fix(sdk): double-cast WorkflowConfig to Record for strict tsc build` — same as #2622 / #2457 rebase, unblocks `npm run build` in `sdk/`. Drop if #2622 lands first.
3. `docs(spec): replace `foo` placeholder with `<cmd>` in gsd-sdk query example` — a new test on main (`gsd-sdk-query-registry-integration`) scans all `.md` files for `gsd-sdk query <token>` patterns and requires the token to be a registered handler. Your spec doc used `foo` as a placeholder which trips the scanner. Replaced with the angle-bracketed placeholder form that the scanner ignores.

Verification: full test suite **5410 pass / 0 fail**. `cd sdk && npm run build` succeeds. CI will re-run from the forced push.

**Comment by trek-e** [comment]
Rebased onto current `main`. Conflicts: `bin/install.js` (kept the capability-probe — the PR's point), `CHANGELOG.md` (kept both Fixed entries side-by-side).

3 commits added on top:
1. TS fix (`WorkflowConfig` cast, same as #2622) — unblocks `npm run build` in sdk/.
2. Doc fix (spec used `foo` as placeholder, trips the new `gsd-sdk-query-registry-integration` test; replaced with `<cmd>`).
3. Your original final commit (`bf87115c` CHANGELOG link fix) replayed cleanly.

Verified: 5410 pass / 0 fail. SDK builds. Force-pushed to your branch.

**Comment by trek-e** [comment]
Update: the conflicts can't be resolved because **the code this PR modifies no longer exists on main**. PR #2457 (merged earlier today) replaced the entire build-from-source path in `installSdkIfNeeded` with a prebuilt-dist shim — there's no `npm run build` at install time anymore, so there's no "should we rebuild?" decision for a capability probe to guard.

Main's current `installSdkIfNeeded` is ~40 lines and only verifies that `sdk/dist/cli.js` exists and is executable; the tarball now ships the built dist directly.

The underlying defect (#2414 — users upgrading from v1.37.1 were stuck on the stale `@gsd-build/sdk@0.1.0`) is structurally fixed by #2457: once a user installs the post-#2457 tarball, the bundled dist supersedes whatever stale global @gsd-build/sdk they had.

This PR's approach was correct for the pre-#2457 architecture and the capability-probe insight is good engineering. But the problem space has shifted — recommend **closing with credit**. Happy to draft the close message if useful.

@trek-e for the call.
