### ISSUE TITLE
[1.37.1] `gsd-sdk query` calls fail — installed `@gsd-build/sdk@0.1.0` exposes only `run|auto|init`, no `query` subcommand

### ISSUE THREAD

**Issue by abouchard11** [glittercowboy/get-shit-done#2393]
## Summary

After updating to v1.37.1, any workflow or agent that invokes `gsd-sdk query <command>` fails because the installed npm package `@gsd-build/sdk@0.1.0` exposes only `run | auto | init` subcommands — there is no `query` dispatcher.

The CHANGELOG for v1.36 describes migrating call sites from `gsd-tools.cjs` to `gsd-sdk query <handler>`, but the `@gsd-build/sdk` package shipped to npm does not implement the `query` dispatcher those workflows depend on.

## Versions

- GSD: v1.37.1 (also reproduces on v1.36.0; works on v1.34.2)
- `@gsd-build/sdk`: 0.1.0 — only version published to npm; `npm view @gsd-build/sdk versions` returns `["0.1.0"]`
- Node: v22.20.0 (via nvm)
- Runtime: Claude Code 2.x on macOS (darwin 25.5.0)

## Reproduction

```bash
$ npm view @gsd-build/sdk version
0.1.0

$ gsd-sdk query validate.health
Error: Expected "gsd-sdk run <prompt>", "gsd-sdk auto", or "gsd-sdk init [input]"
Usage: gsd-sdk <command> [args] [options]

Commands:
  run <prompt>          Run a full milestone from a text prompt
  auto                  Run the full autonomous lifecycle ...
  init [input]          Bootstrap a new project from a PRD ...
```

Or invoke `/gsd-health` from Claude Code — it fails on the first `gsd-sdk query` call in `workflows/health.md`.

## Impact

~40 call sites in v1.37.1 invoke `gsd-sdk query`:

- `workflows/health.md` → `gsd-sdk query validate.health`
- `workflows/execute-plan.md` → `verify.key-links`, `verify.artifacts`
- `workflows/execute-phase.md` → `config-get`, `commit`, `roadmap.update-plan-progress`
- `workflows/progress.md` → `state.load`
- `workflows/complete-milestone.md` → `commit`
- `workflows/profile-user.md` → `frontmatter.get`
- (+ many others — `grep -r "gsd-sdk query" ~/.claude/get-shit-done/`)

Many call sites swallow failures (`|| echo "…"`) so the symptom is silent fallback to defaults. Hard-fail paths like `/gsd-health` error immediately.

## Expected

Either:

1. `@gsd-build/sdk` ships the `query` dispatcher that v1.36+ workflows depend on, or
2. Workflows call `gsd-tools.cjs` directly (as v1.34.2 did — 55 call sites, all functional).

## Workaround

Downgrade to the last npm-published pre-migration release:

```bash
npx get-shit-done-cc@1.34.2 --global
```

v1.35.0 was tagged on GitHub but never published to npm (`npm view get-shit-done-cc versions` skips from `1.34.2` to `1.36.0`), so `1.34.2` is the last npm-reachable working version.

**Comment by DavyMassoneto** [comment]
Same here, i can't use the latest version

**Comment by gauravagnihotristla** [comment]
Cross-reference: PR #2417 should close this on merge + release.

The root cause is the same stale-SDK-on-PATH symptom you documented. PR #2386 already fixed fresh installs by building `@gsd-build/sdk` from in-repo source. PR #2417 closes the remaining gap: the installer's `which gsd-sdk` probe was fooled by the stale `0.1.0` binary v1.37.1 left behind and skipped the rebuild. The new probe runs `gsd-sdk --help` and rebuilds from source if the output doesn't contain `query`.

Tracking the umbrella distribution-gap discussion on #2309.

**Comment by trek-e** [comment]
Closing — the query dispatcher was added in v1.38.0 when the SDK is now built from the in-repo source rather than the frozen @gsd-build/sdk@0.1.0. Update: npm install -g get-shit-done-cc@latest

**Comment by cx18121** [comment]
I hit this same failure today on a fresh-ish Codex setup with `get-shit-done-cc@1.38.3`, so the v1.38.0 fix may not cover all update paths.

Environment:
- Runtime: Codex
- GSD workflow pack: `1.38.3`
- `npm view get-shit-done-cc version`: `1.38.3`
- Existing `gsd-sdk` on PATH: `@gsd-build/sdk@0.1.0`

Repro:

```bash
gsd-sdk --version
# gsd-sdk v0.1.0

gsd-sdk query init.plan-phase 2
# Error: Expected "gsd-sdk run <prompt>", "gsd-sdk auto", or "gsd-sdk init [input]"
```

Then I ran:

```bash
npx -y get-shit-done-cc@latest --codex --global
```

The installer reported:

```text
GSD SDK already installed (gsd-sdk on PATH at .../bin/gsd-sdk)
```

but it did not replace/rebuild the stale SDK, so `gsd-sdk query ...` still failed.

Manual workaround that fixed it locally:

```bash
cd $(npm root -g)/get-shit-done-cc/sdk
npm ci
npm run build
npm install -g $(pwd)
```

After that:

```bash
gsd-sdk --help
# shows query <argv...>

gsd-sdk query init.plan-phase 2
# works
```

So the remaining gap appears to be the installer compatibility check: it detects that `gsd-sdk` exists, but either does not verify that `gsd-sdk --help` contains `query`, or that check is not firing in the Codex/global install path on 1.38.3.
